#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

ATH_IF=""

find_ath_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   ath_dev=`/usr/sbin/status_oper GET "ATH_MAP" "$CPEID"`
   ATH_IF=${ath_dev:3}
   #echo "ATH_IF $ATH_IF "
}

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
   find_ath_if_from_index $1
   eval APNAME=ath${ATH_IF}
   
   ap_dyn_file=/ramdisk/tmp/ap_dyn_file
   rm -f ${ap_dyn_file}
   
   ifconfig ${APNAME} >>${ap_dyn_file}
   iwconfig ${APNAME} >>${ap_dyn_file}
   
    UP_STATUS=$(grep "UP" ${ap_dyn_file})
    if [ "${UP_STATUS}" = "" ]; then
        status=0
    else
        status=1
    fi
    
    echo "status=\"$status\""
    if [ ${status} = "1" ]; then
        Bssid=$(grep "Access Point" ${ap_dyn_file} |  cut -d ":" -f 4,5,6,7,8,9 | cut -d " " -f 2)
        PossblDataRates=$(grep "Bit Rate" ${ap_dyn_file} | cut -d ":" -f 2 | cut -d " " -f 1,2)
        echo "bssid=\"$Bssid\""
        echo "possblDataRates=\"$PossblDataRates\""
    else
        Bssid=$(grep "HWaddr" ${ap_dyn_file} | cut -d ":" -f 2,3,4,5,6,7,8 | cut -d " " -f 4)
        PossblDataRates=$(grep "Bit Rate" ${ap_dyn_file} | cut -d ":" -f 2 | cut -d " " -f 1,2)
        echo "bssid=\"$Bssid\""
        echo "possblDataRates=\"$PossblDataRates\""    
    fi
fi

