#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
    eval APNAME=ath${1}

    #HOSTAPD_VER=`/sbin/hostapd -v 2>&1 | grep hostapd | cut -f2 -d' '`
	
    hostapd_cli_ath -i ${APNAME} wps_pbc
fi
