#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

ATH_IF=""

find_ath_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   ath_dev=`/usr/sbin/status_oper GET "ATH_MAP" "$CPEID"`
   ATH_IF=${ath_dev:3}
   #echo "ATH_IF $ATH_IF "
}

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
    find_ath_if_from_index $1
    eval APNAME=ath${ATH_IF}
    
    ap_stat_file=/tmp/stat
    rm -f $ap_stat_file
    
    80211stats -i ${APNAME} >> ${ap_stat_file}
    ifconfig ${APNAME} >> ${ap_stat_file}
    
    bytesTx=$(grep "TX bytes" $ap_stat_file | cut -d ":" -f 3 | cut -d " " -f 1)
    bytesRx=$(grep "TX bytes" $ap_stat_file | cut -d ":" -f 2 | cut -d " " -f 1)
    pktsTx=$(grep "TX packets" $ap_stat_file | cut -d ":" -f 2 | cut -d " " -f 1)
    pktsRx=$(grep "RX packets" $ap_stat_file | cut -d ":" -f 2 | cut -d " " -f 1)
    errorsTx=$(grep "TX packets" $ap_stat_file | cut -d ":" -f 3 | cut -d " " -f 1)
    errorsRx=$(grep "RX packets" $ap_stat_file | cut -d ":" -f 3 | cut -d " " -f 1)
    discardPktsTx=$(grep "TX packets" $ap_stat_file | cut -d ":" -f 4 | cut -d " " -f 1)
    discardPktsRx=$(grep "RX packets" $ap_stat_file | cut -d ":" -f 4 | cut -d " " -f 1)
    
    ucPktsTx=$(grep "transmitted" $ap_stat_file | cut -d " " -f 1 | sed -n "1p")
    ucPktsRx=$(grep "received" $ap_stat_file | cut -d " " -f 1 | sed -n "1p")
    mcPktsTx=$(grep "transmitted" $ap_stat_file | cut -d " " -f 1 | sed -n "2p")
    mcPktsRx=$(grep "received" $ap_stat_file | cut -d " " -f 1 | sed -n "2p")
    bcPktsTx=0
    bcPktsRx=0
    
    if [ "$errorsTx" = "" ]; then
    	errorsTx=0
    fi
    if [ "$errorsRx" = "" ]; then
    	errorsRx=0
    fi
    if [ "$discardPktsTx" = "" ]; then
    	discardPktsTx=0
    fi
    if [ "$discardPktsRx" = "" ]; then
    	discardPktsRx=0
    fi
    
    if [ "$ucPktsTx" = "" ]; then
    	ucPktsTx=0
    fi
    if [ "$mcPktsTx" = "" ]; then
    	mcPktsTx=0
    fi
    if [ "$ucPktsRx" = "" ]; then
    	ucPktsRx=0
    fi
    if [ "$mcPktsRx" = "" ]; then
    	mcPktsRx=0
    fi
    
#    pktsTx=`expr $ucPktsTx + $mcPktsTx`
#    pktsRx=`expr $ucPktsRx + $mcPktsRx`
    
    echo "bytesTx=\""$bytesTx"\""
    echo "bytesRx=\""$bytesRx"\""
    echo "pktsTx=\""$pktsTx"\""
    echo "pktsRx=\""$pktsRx"\""
    echo "errorsTx=\""$errorsTx"\""
    echo "errorsRx=\""$errorsRx"\""
    echo "discardPktsTx=\""$discardPktsTx"\""
    echo "discardPktsRx=\""$discardPktsRx"\""
    echo "ucPktsTx=\""$ucPktsTx"\""
    echo "ucPktsRx=\""$ucPktsRx"\""
    echo "mcPktsTx=\""$mcPktsTx"\""
    echo "mcPktsRx=\""$mcPktsRx"\""
    echo "bcPktsTx=\""$bcPktsTx"\""
    echo "bcPktsRx=\""$bcPktsRx"\""
fi
