#!/bin/sh


if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

ATH_IF=""

find_ath_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   ath_dev=`/usr/sbin/status_oper GET "ATH_MAP" "$CPEID"`
   ATH_IF=${ath_dev:3}
   #echo "ATH_IF $ATH_IF "
}

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
    find_ath_if_from_index $1
    eval APNAME=ath${ATH_IF}
    wps_dyn_file=/tmp/WSC_${APNAME}.conf

    HOSTAPD_VER=`/sbin/hostapd_ath -v 2>&1 | grep hostapd | cut -f2 -d' '`
    if [ "${HOSTAPD_VER}" = "v0.5.9" ]; then
    	wpsVersion="0x10"
    	wpsState=$(grep "wps_configured" ${wps_dyn_file} |  cut -d "=" -f 2)
    else
	wpsVersion="0x20"
	wpsState=$(grep "wps_state" ${wps_dyn_file} |  cut -d "=" -f 2)
    fi
    
    echo "wpsVersion=\"$wpsVersion\""
    if [ "${wpsState}" = "1" ]; then	
    	wpsState=0
    else
	wpsState=1
    fi
    echo "configState=\"$wpsState\""
fi
