#!/bin/sh

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		 . /etc/rc.conf 2> /dev/null
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh 2>/dev/null
		CONFIGLOADED="1"
	fi
fi

ATH_IF=""

find_ath_if_from_index() {
   eval CPEID='$'wlmn_${1}'_cpeId'
   ath_dev=`/usr/sbin/status_oper GET "ATH_MAP" "$CPEID"`
   ATH_IF=${ath_dev:3}
   #echo "ATH_IF $ATH_IF "
}

if [ "$CONFIG_FEATURE_IFX_WIRELESS" = "1" ]; then
    find_ath_if_from_index $1
    eval APNAME=ath${ATH_IF}
    
    wps_ap_pin_file=/tmp/wps_ap_pin_file
    rm -f ${wps_ap_pin_file}
        
    HOSTAPD_VER=`/sbin/hostapd_ath -v 2>&1 | grep hostapd | cut -f2 -d' '`
    if [ "${HOSTAPD_VER}" = "v0.5.9" ]; then
    	PIN=$(wpatalk ${APNAME} pin | grep "PIN"  | cut -d "=" -f 3 | cut -d " " -f 2)
    	echo "PIN=${PIN}" >${wps_ap_pin_file}
    
    	wpatalk $APNAME "configthem pin=${PIN}" &
    else
	hostapd_cli_ath -i ${APNAME} wps_ap_pin random
        PIN=$(hostapd_cli_ath -i ${APNAME} wps_ap_pin get)
	echo "PIN=${PIN}" >${wps_ap_pin_file}
    fi    
fi
