#!/bin/sh /etc/rc.common

START=00

start() {
	echo "System Init..."
	
	if [ ! "$ENVLOADED" ]; then
		if [ -r /etc/rc.conf ]; then
			 . /etc/rc.conf 2> /dev/null
			ENVLOADED="1"
		fi
	fi

	if [ ! "$CONFIGLOADED" ]; then
		if [ -r /etc/rc.d/config.sh ]; then
			. /etc/rc.d/config.sh 2>/dev/null
			CONFIGLOADED="1"
		fi
	fi

	. /etc/functions.sh

	[ `mount|grep -q nfs;echo $?` -eq  0 ] || /sbin/ifconfig eth0 0.0.0.0 up 2>/dev/null
	cd /tmp
	chmod 777 .

	tar xvf /dev/mtdblock3 -C /tmp

	if  true ; then
		## read current config
		/usr/sbin/read_img sysconfig /ramdisk/flash/rc.conf.gz
		/bin/gunzip -f /ramdisk/flash/rc.conf.gz 2>/dev/null
		if [ $? -ne 0 ]; then
			/bin/rm -f /ramdisk/flash/rc.conf
			/usr/sbin/upgrade /etc/rc.conf.gz sysconfig 0 1 2>/dev/null
			/usr/sbin/read_img sysconfig /ramdisk/flash/rc.conf.gz
			/bin/gunzip -f /ramdisk/flash/rc.conf.gz
		fi

		mount -t ubifs ubi0:defconfig /sysconfig && {
			if [ ! -f /sysconfig/jnr-cfg.ascii ] ; then
				echo "Loading default ascii!!"
				cp /usr/local/etc/jnr-cfg.ascii.default /sysconfig/jnr-cfg.ascii
				/usr/local/bin/update_to_default_config_essid.sh  /sysconfig/jnr-cfg.ascii
				/usr/local/bin/update_to_default_config.sh  /sysconfig/jnr-cfg.ascii
				/usr/local/bin/update_to_default_config_sn.sh  /sysconfig/jnr-cfg.ascii
				/usr/local/bin/update_to_default_config_wpakey.sh /sysconfig/jnr-cfg.ascii
				/usr/local/bin/update_to_default_config_imei.sh   /sysconfig/jnr-cfg.ascii
			else
				echo "Using current ascii!!"
			fi
		}  || {
			echo "Recreate defconfig partition!!"
			ubirmvol /dev/ubi0 -N defconfig
			ubimkvol /dev/ubi0 -s 0x200000 -N defconfig
			/usr/sbin/vol_mgmt create_ubi_nodes
			mount -t ubifs ubi0:defconfig /sysconfig
			echo "Loading default ascii!!"
			cp /usr/local/etc/jnr-cfg.ascii.default /sysconfig/jnr-cfg.ascii
			/usr/local/bin/update_to_default_config_essid.sh  /sysconfig/jnr-cfg.ascii
					/usr/local/bin/update_to_default_config.sh  /sysconfig/jnr-cfg.ascii
					/usr/local/bin/update_to_default_config_sn.sh  /sysconfig/jnr-cfg.ascii
					/usr/local/bin/update_to_default_config_wpakey.sh /sysconfig/jnr-cfg.ascii
					/usr/local/bin/update_to_default_config_imei.sh /sysconfig/jnr-cfg.ascii
		}
	fi
	
	DBInit &
	/etc/init.d/passwd.sh start
}
