#!/bin/sh /etc/rc.common

START=11

start() {
	echo "disable PHY..."
	switch_utility PortLinkCfgSet 0 0 0 0 10 1 1 0 0 0
	switch_utility PortLinkCfgSet 1 0 0 0 10 1 1 0 0 0
	switch_utility PortLinkCfgSet 2 0 0 0 10 1 1 0 0 0
	switch_utility PortLinkCfgSet 4 0 0 0 10 1 1 0 0 0
}
